server:
  port: 8000

spring:
  application:
    name: default-prod-service

  datasource:
    url: jdbc:h2:mem:default-prod-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

